swagger: "2.0"
info:
  version: 1.0.0
  title: GroundSchool NZ API
  contact:
    email: groundschoolnz@gmail.com
host: gs-api-prod.appspot.com
basePath: /api
paths:
  /exams:
    get:
      summary: return list of exams
      operationId: listExams
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ExamResponse'
            properties:
              results:
                type: array
                items:
                  $ref: '#/definitions/ExamResponse'

  /exams/{examId}:
    get:
      summary: return exam by id
      operationId: getExamById
      parameters:
      - in: path
        name: examId
        description: ID of exam
        required: true
        type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ExamResponse'
        '404':
          description: not found

definitions:
  ExamResponse:
    type: object
    required:
      - name
      - licenseType
      - slug
    properties:
      id:
        type: string
      name:
        type: string
      licenseType:
        $ref: '#/definitions/LicenseType'
      slug:
        type: string
      availableQuestions:
        type: integer
      aspeqName:
        type: string
      aspeqExamInfo:
        $ref: '#/definitions/ExamInfo'
      currentExamInfo:
        $ref: '#/definitions/ExamInfo'
      questions:
        type: array
        items:
          $ref: '#/definitions/ExamQuestion'

  LicenseType:
    type: string
    enum:
      - ppl
      - cpl
      - ir
      - other

  ExamInfo:
    type: object
    properties:
      durationMinutes:
        type: integer
      numberOfQuestions:
        type: integer
      allowedMaterials:
        type: array
        items:
          $ref: '#/definitions/AllowedMaterial'

  AllowedMaterial:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      purchaseUrl:
        type: string

  ExamQuestion:
    type: object
    required:
      - text
      - answers
      - correctAnswerId
    properties:
      id:
        type: string
      text:
        type: string
      answers:
        type: array
        items:
          $ref: '#/definitions/ExamAnswer'
      correctAnswerId:
        type: string
      selectedAnswerId:
        type: string
      assetPaths:
        type: array
        items:
          type: string
      status:
        $ref: '#/definitions/ExamQuestionStatus'

  ExamAnswer:
    type: object
    required:
      - text
    properties:
      id:
        type: string
      text:
        type: string

  ExamQuestionStatus:
    type: string
    enum:
      - unanswered
      - answered
      - review